# Generated by Django 5.2.3 on 2025-06-23 16:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("email_verification_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("email_verification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email address")),
                ("first_name", models.CharField(max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(max_length=150, verbose_name="last name")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True, verbose_name="date of birth")),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/%Y/%m/%d/", verbose_name="avatar"),
                ),
                ("marketing_consent", models.BooleanField(default=False, verbose_name="marketing consent")),
                ("newsletter_subscription", models.BooleanField(default=False, verbose_name="newsletter subscription")),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="last login IP")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "google_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Google ID"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "auth_user",
            },
        ),
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_jti", models.CharField(max_length=255, unique=True, verbose_name="token JTI")),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True, verbose_name="blacklisted at")),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacklisted Token",
                "verbose_name_plural": "Blacklisted Tokens",
                "db_table": "blacklisted_tokens",
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "address_type",
                    models.CharField(
                        choices=[("shipping", "Shipping"), ("billing", "Billing"), ("both", "Both")],
                        default="both",
                        max_length=10,
                        verbose_name="address type",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="first name")),
                ("last_name", models.CharField(max_length=100, verbose_name="last name")),
                ("company", models.CharField(blank=True, max_length=100, verbose_name="company")),
                ("address_line1", models.CharField(max_length=255, verbose_name="address line 1")),
                ("address_line2", models.CharField(blank=True, max_length=255, verbose_name="address line 2")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("state", models.CharField(max_length=100, verbose_name="state/province")),
                ("postal_code", models.CharField(max_length=20, verbose_name="postal code")),
                ("country", models.CharField(max_length=2, verbose_name="country")),
                ("is_default", models.BooleanField(default=False, verbose_name="is default")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
                "db_table": "user_addresses",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="auth_user_email_ece7f7_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="auth_user_created_2cecd0_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active", "is_email_verified"], name="auth_user_is_acti_0531df_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["google_id"], name="auth_user_google__39783d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email_verification_token"], name="auth_user_email_v_01246a_idx"),
        ),
        migrations.AddIndex(
            model_name="blacklistedtoken",
            index=models.Index(fields=["token_jti"], name="blacklisted_token_j_36f8ca_idx"),
        ),
        migrations.AddIndex(
            model_name="blacklistedtoken",
            index=models.Index(fields=["user"], name="blacklisted_user_id_a5837f_idx"),
        ),
        migrations.AddIndex(
            model_name="blacklistedtoken",
            index=models.Index(fields=["expires_at"], name="blacklisted_expires_d1bb66_idx"),
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(fields=["user", "is_default"], name="user_addres_user_id_35ed52_idx"),
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(fields=["user", "address_type"], name="user_addres_user_id_8ff364_idx"),
        ),
        migrations.AddConstraint(
            model_name="useraddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user", "address_type"),
                name="unique_default_address_per_type",
            ),
        ),
    ]
